apiVersion: v1
kind: Namespace
metadata:
  name: poc

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-monitor-config
  namespace: poc
data:
  ARGOCD_API: "https://argocd-server.argocd.svc.cluster.local/api/v1"

---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-monitor-secret
  namespace: poc
type: Opaque
data:
  ARGOCD_TOKEN: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKaGNtZHZZMlFpTENKemRXSWlPaUpoWkcxcGJqcGhjR2xMWlhraUxDSnVZbVlpT2pFM05EUXdNelUxT1RBc0ltbGhkQ0k2TVRjME5EQXpOVFU1TUN3aWFuUnBJam9pWmpsbE9XRTRZalF0WVdZMk15MDBZalk1TFRreVkyRXRaakUwWkRrME5qSXlaV05tSW4wLjNvOElWVGJfZHVlUmh5NVZ0MGlyRWF2TXNybHlHOTNVMHQ1SERNc0lGTWM=

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-monitor-sa
  namespace: poc

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-monitor-role
  namespace: poc
rules:
  - apiGroups: [""]
    resources: ["pods", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["get", "list", "watch", "sync", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-monitor-rolebinding
  namespace: poc
subjects:
  - kind: ServiceAccount
    name: argocd-monitor-sa
    namespace: poc
roleRef:
  kind: Role
  name: argocd-monitor-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-monitor
  namespace: poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-monitor
  template:
    metadata:
      labels:
        app: argocd-monitor
    spec:
      serviceAccountName: argocd-monitor-sa
      containers:
        - name: argocd-monitor
          image: jaimehenao8126/argocd-monitor:latest
          env:
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: slack-webhook-secret
                  key: SLACK_WEBHOOK_URL
          envFrom:
            - configMapRef:
                name: argocd-monitor-config
            - secretRef:
                name: argocd-monitor-secret
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
