apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-admin-rolebinding
  namespace: argocd
subjects:
  - kind: User
    name: admin # Usuario admin
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: argocd-server # Rol con permisos completos
  apiGroup: rbac.authorization.k8s.io
