apiVersion: batch/v1
kind: CronJob
metadata:
  name: argocd-monitor
  namespace: poc
spec:
  schedule: "*/5 * * * *" # Cambiado para ejecutar cada 5 minutos
  successfulJobsHistoryLimit: 1 # Mantener solo 1 job exitoso en el historial
  failedJobsHistoryLimit: 1 # Mantener solo 1 job fallido en el historial
  concurrencyPolicy: Forbid # Evitar que se ejecuten múltiples instancias al mismo tiempo
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: argocd-monitor-sa
          containers:
            - name: argocd-monitor
              image: jaimehenao8126/argocd-monitor:latest
              envFrom:
                - configMapRef:
                    name: argocd-monitor-config
                - secretRef:
                    name: argocd-monitor-secret
              resources:
                limits:
                  memory: "256Mi"
                  cpu: "500m"
                requests:
                  memory: "128Mi"
                  cpu: "250m"
          restartPolicy: OnFailure
