name: CD

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!README.md'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME_JAIME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD_JAIME }}
  IMAGE_NAME: argocd-monitor

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME_JAIME }}
          password: ${{ env.DOCKER_PASSWORD_JAIME }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_USERNAME_JAIME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} -f ./Dockerfile .

      - name: Push Docker image
        run: |
          docker push ${{ env.DOCKER_USERNAME_JAIME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Update deployment.yaml and commit
        run: |
          sed -i 's|image:.*|image: '${{ env.DOCKER_USERNAME_JAIME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}'|' ./argocd-monitor.yaml
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add ./argocd-monitor.yaml
          git commit -m "Update deployment.yaml with new image tag" || echo "No changes to commit"
          git push
