name: Rollback Application

on:
  workflow_dispatch:  # Permite ejecutar el workflow manualmente
    inputs:
      app_name:
        description: "Nombre de la aplicación a realizar rollback"
        required: true
      commit_hash:
        description: "Hash del commit al que se desea hacer rollback"
        required: true
  repository_dispatch:  # Permite que el workflow sea disparado automáticamente
    types:
      - trigger-rollback  # Tipo de evento personalizado

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
    # Checkout del repositorio
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Asegura que se obtenga todo el historial del repositorio

    # Configurar Git
    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    # Log Inputs
    - name: Log Inputs
      run: |
        echo "App Name: ${{ github.event.client_payload.app_name }}"
        echo "Commit Hash: ${{ github.event.client_payload.commit_hash }}"

    # Validar el commit hash
    - name: Validate Commit Hash
      run: |
        if ! git cat-file -e ${{ github.event.client_payload.commit_hash }}^{commit}; then
          echo "El commit hash proporcionado no es válido."
          exit 1
        fi

    # Revertir al commit especificado
    - name: Revert to Commit
      run: |
        git revert ${{ github.event.client_payload.commit_hash }} --no-commit
        git commit -m "Rollback for application ${{ github.event.client_payload.app_name }} to commit ${{ github.event.client_payload.commit_hash }}"
        git push origin main

    # Notificar a Slack
    - name: Notify Slack
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        if [[ "${{ job.status }}" == "success" ]]; then
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "Rollback completado para la aplicación: ${{ github.event.client_payload.app_name }}. Revertido al commit: ${{ github.event.client_payload.commit_hash }}."
          }' $SLACK_WEBHOOK_URL
        else
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "El rollback para la aplicación: ${{ github.event.client_payload.app_name }} falló. Requiere intervención manual."
          }' $SLACK_WEBHOOK_URL